
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    #    url: jdbc:mysql://localhost:3306/registration
    url: jdbc:mysql://localhost:3307/elearning
    username: root
    password: root
    #    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9090
video:
  storage:
    location: uploads/videos