
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: p85332398@gmail.com
    password: hlul klll wzmi hrmk
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    #    url: jdbc:mysql://localhost:3306/registration
    url: jdbc:mysql://localhost:3307/elearning
    username: root
    password: 1234
    #    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 9090
video:
  storage:
    location: uploads/videos